baseURL = 'https://ryvlabs.com/'
languageCode = 'en-gb'
title = 'RYV Labs'
theme = 'ryv-design'

[params]
description = "RYV Labs - Technology Transformation Consultancy"
author = "RYV Labs"
logo = "/images/logo.png"
favicon = "/images/favicon.ico"
copyright =   "Â© 2026 RYV Ltd. All rights reserved."