baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'RYV Labs'
theme = 'ryv-design'

[params]
description = "RYV Labs - Technology Transformation Consultancy"

[[menu.main]]
name = "Work"
url = "/work"

[[menu.main]]
name = "Services"
url = "/services"

[[menu.main]]
name = "About"
url = "/about"

[[menu.main]]
name = "Contact"
url = "/contact"